melakartas:
  - Kanakambari
  - Phenadhyuti
  - Ganasamavarali
  - Bhanumati
  - Manoranjani
  - Tanukeerti
  - Senagrani
  - Janatodi
  - Dhunibhinnashadjam
  - Natabharanam
  - Kokilaravam
  - Geya Hejjajji
  - Vatee Vasantabhairavi
  - Toyavegavahini
  - Chayavathi
  - Jayashuddhamalavi
  - Jhankarabhramari
  - Narērētigowla
  - Keeranavali
  - Shree
  - Gowrivelavali
  - Veeravasantham
  - Sharavathi
  - Tarangini
  - Sowrasena
  - Harikedaragowla
  - Nagabharanam
  - Kalavathi
  - Ragachoodamani
  - Gangatarangini
  - Bhogachaya Nattai
  - Shailadeshakshhi
  - Sowgandhini
  - Jaganmohinam
  - Dhalivarali
  - Nabhomani
  - Kumbhini
  - Ravi Kriya
  - Geervani
  - Bhavani
  - Shivapanthuvarali
  - Sthavarajam
  - Sowveeram
  - Jeevanthika
  - Dhavalangam
  - Namadeshi
  - Kashiramakriya
  - Ramamanohari
  - Gamakakriya
  - Vamshavathi
  - Shyamalam
  - Chamaram
  - Deshisimharavam
  - Dhamavathi
  - Nisshadham
  - Kunthalam
  - Rathipriya
  - Geethapriya
  - Bhooshavathi
  - Shanthakalyani
  - Chaturangini
  - Santhana Manjari
  - Jyothi
  - Dhowtha Panchamam
  - Nasamani
  - Kusumakaram
  - Rasamanjari

janyas:
  - Kanakatodi
  - Karnataka Shuddha Saveri
  - Latantapriya
  - Lavangi
  - Megha
  - Rishabhavilasa
  - Sarvashree
  - Suddha Mukhari
  - Tatillatika
  - Vageeshwari
  - Ganamukhari
  - Ratnavarali
  - Revati
  - Shreemani
  - Shreemati
  - Bhinnapanchamam
  - Nadharanjani
  - Poorvavarali
  - Samavarali
  - Rasali
  - Vanavali
  - Vittalapriya
  - Ghanashyamala
  - Kunjari
  - Bhogi
  - Chitthakarshani
  - Navarasa Mala
  - Sindhu Gowri
  - Amrita Dhanyasi
  - Asaveri
  - Bhanuchandrika
  - Bhadratodi
  - Bhoopalam
  - Chandrikatodi
  - Deshikatodi
  - Dhanyasi
  - Divyamalati
  - Ghanta
  - Kalasaveri
  - Kanakasaveri
  - Nagavarali
  - Prabhupriya
  - Punnagatodi
  - Punnagavarali
  - Shravanamallika
  - Sowjanya
  - Shuddha Seemantini
  - Shuddha Todi
  - Swarnamalli
  - Bhinnashadjam
  - Mohananata
  - Vasanthatodi
  - Alankarapriya
  - Bhagyashabari
  - Deeparamu
  - Gunavati
  - Hindoladeshikam
  - Kanakadri
  - Matangakamini
  - Natyadharana
  - Niranjana
  - Shanthabhashini
  - Shivashakti
  - Sindhubhairavi
  - Chitramani
  - Jnanachintamani
  - Kowmari
  - Shuddha Lalitha
  - Vardhani
  - Vasantamalli
  - Vasantanarayani
  - Rowpyanaka
  - Shyamakalyani
  - Hejjajji
  - Kalakanti
  - Kalkada
  - Kalpanadharini
  - Āhiri
  - Amudhasurabhi
  - Devipriya
  - Kalindaja
  - Kuvalayabharanam
  - Sallapa
  - Soma
  - Sūrya
  - Shuddha Kambhoji
  - Vasantabhairavi
  - Vasanta Mukhari
  - Vijayollasini
  - Ardhradesi
  - Bhavini
  - Bibhas
  - Bowli
  - Bowli Ramakriya
  - Charuvardhani
  - Chayagowla
  - Chandrachooda
  - Deshyagowla
  - Devaranji
  - Ekakshari
  - Ghanasindhu
  - Gowla
  - Gowlipantu
  - Gowri
  - Gummakambhoji
  - Gundakriya
  - Gurjari
  - Jaganmohini
  - Kalyanakesari
  - Kannadabangala
  - Karnataka Saranga
  - Lalita
  - Lalitapanchamam
  - Malavakurinji
  - Malavapanchamam
  - Margadesi
  - Malahari
  - Mallikavasantam
  - Mangalakaishiki
  - Manolayam
  - Maruva
  - Mechabowli
  - Megharanjani
  - Nadhanamakriya
  - Padi
  - Pharaju (Paras)
  - Poornalalita
  - Poorvi
  - Poorvikavasanta
  - Pratapadhanyasi
  - Prataparanjani
  - Puranirmai
  - Ramakali
  - Ramakriya
  - Revagupti
  - Rukhmambari
  - Samantadeepara
  - Saranga Nata
  - Saveri
  - Salanganata
  - Satyavati
  - Sindhu Ramakriya
  - Surasindhu
  - Tarakagowla
  - Takka
  - Ushavali
  - Visharada
  - Āhir Bhairavi
  - Bhakthapriya
  - Bhujangini
  - Bindhumalini
  - Chakranarayani
  - Ghoshini
  - Guhapriya
  - Kalavati
  - Kokila
  - Malayamarutam
  - Mukthangi
  - Mukundamalini
  - Poornapanchamam
  - Pravritti
  - Ragamanjari
  - Rasikaranjani
  - Shree Nabhomargini
  - Shyamali
  - Subhashini
  - Valaji
  - Veenadhari
  - Vegavahini
  - Bhairavam
  - Haridarpa
  - Jayasamvardhani
  - Jeevantika
  - Kusumamaruta
  - Nagachooḍamani
  - Rohini
  - Samakannada
  - Sowrashtram
  - Suddha Gowla
  - Supradeepam
  - Vasantha
  - Hamsanantini
  - Kallola
  - Simhala
  - Bharati
  - Jalmika
  - Lalitabhairavi
  - Poornalalita
  - Anandabhairavi
  - Amrithavahini
  - Bhairavi
  - Bhuvanagandhari
  - Chapagantarva
  - Darbari Kanada
  - Devakriya
  - Dhanashree
  - Dharmaprakashini
  - Dilipika Vasantha
  - Divyagandhari
  - Gopikavasantam
  - Hindolam
  - Hindolavasanta
  - Indughantarava
  - Jayanthashrī
  - Jingaḷa
  - Jonpuri
  - Katyayani
  - Kanakavasantham
  - Kshanika
  - Manji
  - Mahati
  - Malkosh
  - Nagagandhari
  - Navarathna Vilasam
  - Nīlamati
  - Nīlaveni
  - Poornashađjam
  - Rajarajeshwari
  - Saramati
  - Saranga Kapi
  - Sharadapriya
  - Shree Navarasachandrika
  - Sindhu Dhanyasi
  - Shuddha Desi
  - Shuddha Salavi
  - Sukumari
  - Sushama
  - Sutradhari
  - Tarkshika
  - Udayaraga
  - Vasantavarali
  - Aymmukhan
  - Bhanupriya
  - Chandrika
  - Gaganabhoopalam
  - Hamsapancama
  - Hamsavahini
  - Jayashree
  - Kadaram (Chandrakosh, Chandrakauns, Chandrakaush)
  - Kalyana Vasantam
  - Kusumavali
  - Madhavi
  - Mishramanolayam
  - Priyadarshani
  - Rishipriya
  - Samapriya
  - Shrothasvini
  - Vasanthamanohari
  - Abheri
  - Abhogi
  - Ādi Kapi
  - Āryamati
  - Agnikopa
  - Asaveri
  - Balachandrika
  - Basant Bahar
  - Bhageshri
  - Bhagavatapriya
  - Bhagavathpriya
  - Bhimpalas
  - Brindavana Saranga
  - Brindavani
  - Chakrapradipta
  - Chittaranjani
  - Darbar
  - Dayavati
  - Devamruthavarshani
  - Deva Manohari
  - Dhanakapi
  - Dilipika
  - Durga
  - Gowla Kannada
  - Hamsa abheri
  - Haridasapriya
  - Harinarayani
  - Hindustani Kapi
  - Huseni
  - Jayamanohari
  - Jayanarayani
  - Jayanthasena
  - Kanada
  - Kapi
  - Kapijingala
  - Kalanidhi
  - Kalika
  - Kannadagowla
  - Karnataka Hindolam
  - Karnataka Kapi
  - Karnaranjani
  - Kowmodaki
  - Kowshika
  - Lalitamanohari
  - Madhavamanohari
  - Malavashree
  - Margahindolam
  - Mayapradeeptam
  - Madhyamaravali
  - Madhyamavathi
  - Mahanandhi
  - Mandamari
  - Mangalavathi
  - Manirangu
  - Manjari
  - Manohari
  - Manorama
  - Maruvadhanyasi
  - Mishramanolayam
  - Mishrashivaranjani
  - Miyan Malhar
  - Mukhari
  - Nadachintamani
  - Nadatarangini
  - Nadavarangini
  - Nagari
  - Nagavalli
  - Nayaki
  - Nigamagamini
  - Nirmalangi
  - Omkari
  - Panchamam
  - Patadeep
  - Phalamanjari
  - Phalaranjani
  - Peeloo
  - Poornakalanidhi
  - Pushpalathika
  - Ratipatipriya
  - Reethigowla
  - Rudrapriya
  - Salagabhairavi
  - Sarang
  - Saindhavi
  - Sangrama
  - Sankrandanapriya
  - Sarvachoodamani
  - Shivapriya
  - Shivaranjani
  - Shree Manohari
  - Shree Manoranjani
  - Shreeranjani
  - Siddhasena
  - Suddha Bangala
  - Suddha Bhairavi
  - Suddha Dhanyasi
  - Suddha Hindolam
  - Suddha Manohari
  - Suddha Velavali
  - Sugunabhooshani
  - Swarabhooshani
  - Swarakalanidhi
  - Swararanjani
  - Tavamukhari
  - Vajrakanti
  - Gowrishankar
  - Hamsadeepika
  - Hrudkamali
  - Lavanthika
  - Sundaramanohari
  - Vasantashree (Amba Manohari)
  - Velavali
  - Devasalaga
  - Jana Sammodhini
  - Kesari
  - Rajathilaka
  - Chirswaroopi
  - Maravi
  - Poorvadhanyasi
  - Shiva Manohari
  - Shukrajyothi
  - Haripriya
  - Kamala Manohari
  - Madhulika
  - Nalinakanthi
  - Neelamani
  - Salavi
  - Sarasanana
  - Saraseeruha
  - Simhavahini
  - Surasena
  - Sutradhari
  - Vasanthi
  - Andolika
  - Ambhojini
  - Andhali
  - Aparoopam
  - Balahamsa
  - Bahudari
  - Bhoopali
  - Chayalagakhamas
  - Chayatarangini
  - Chandrahasitham
  - Dasharatipriya
  - Dayaranjani
  - Desh
  - Deshakshi
  - Deshkar
  - Dwaithachintamani
  - Dwijavanthi
  - Eeshamanohari
  - Eeshaivaridhi
  - Gandharalola
  - Gavathi
  - Guhamanohari
  - Guharanjani
  - Hamsaroopini
  - Haridasapriya
  - Harikedaram
  - Harini
  - Harithapriya
  - Hemasaranga
  - Jaijaivanthi
  - Jaithshree
  - Jana Sammodhini
  - Jayarama
  - Jhinjothi
  - Jog (Hindustani)
  - Jujahuli
  - Kambhoji
  - Kapi Narayani
  - Kamas
  - Karnataka Behag
  - Karnataka Devagandhari
  - Karnataka Khamas
  - Kedaragowla
  - Keshavapriya
  - Kokiladhwani
  - Kokilavarali
  - Kunthalavarali
  - Malavi
  - Madhurakokila
  - Mahathi
  - Mahuri
  - Manjupriya
  - Manoharam
  - Mattakokila
  - Meghana
  - Mohanam
  - Nadavalli
  - Nagaswaravali
  - Narayanagowla
  - Narayani
  - Nattai Kurinji
  - Nattai Narayani
  - Nandhkowns
  - Narani
  - Navarasa Kalanidhi
  - Navarasa Kannada
  - Neela
  - Parsi
  - Parameshwarapriya
  - Pashupathipriya
  - Poornakambhoji
  - Pratapa Nattai
  - Pratapavarali
  - Pravalajyoti
  - Ragapanjaramu
  - Ragavinodini
  - Rageshree
  - Ravi Chandrika
  - Savithri
  - Sahana
  - Saraswathi Manohari
  - Sathvamanjari
  - Shakunthala
  - Shankaraharigowla
  - Shenchukambhoji
  - Chenjurutti
  - Shiva Kambhoji
  - Surutti
  - Shyama
  - Simhavikrama
  - Sindhu Kannada
  - Sindhu Surutti
  - Suddha Khamas
  - Suddha Varali
  - Suddha
  - Suddhatarangini
  - Sumanapriya
  - Suposhini
  - Suvarnakriya
  - Swaravali
  - Swaravedi
  - Tilakavathi
  - Thilang
  - Umabharanam
  - Vaishnavi
  - Veenavadini
  - Vivardhani
  - Yadukula Kambhoji
  - Ānandharoopa
  - Ārabi
  - Atana
  - Bangala
  - Begada
  - Behag
  - Behag Deshikam
  - Bilahari
  - Buddhamanohari
  - Buddharanjani
  - Chaya
  - Chayashankarabharanam
  - Devagandhari
  - Dharmalakhi
  - Dhurvanki
  - Gajagowri
  - Garudadhvani
  - Gowdamalhar
  - Hamsadhwani
  - Hamsavinodhini
  - Hemant
  - Hindustani Behag
  - Janaranjani
  - Julavu
  - Kamaripriya
  - Kannada
  - Kadanakuthoohalam
  - Kedaram
  - Kokilabhashani
  - Kolahalam
  - Kurinji
  - Kusumavichithra
  - Kutuhala
  - Lahari
  - Mand
  - Mayadravila
  - Mohanadhwani
  - Nagabhooshani
  - Nagadhwani
  - Narayanadeshakshi
  - Navaroj
  - Neelambari
  - Niroshta
  - Pahadi
  - Poornachandrika
  - Poornagowla
  - Poorvagowla
  - Rathnabhooshani
  - Reetuvilasa
  - Saranga Mallar
  - Shankara
  - Shankaraharigowla
  - Shankaramohana
  - Shankari
  - Sindhu
  - Sindhu Mandari
  - Suddha Malavi
  - Suddha Sarang
  - Suddha Saveri
  - Suddha Vasantha
  - Suranandini
  - Suraranjani
  - Tandavam
  - Vallabhi
  - Vasanthamalai
  - Vedhandhagamana
  - Veerapratapa
  - Vilasini
  - Gambheeravani
  - Lalithagandharva
  - Samanta
  - Thilang
  - Damarugapriya
  - Desharanjani
  - Deshyathodi
  - Ganavaridhi
  - Kalahamsa
  - Niranjani
  - Prathapahamsi
  - Amudagandhari
  - Dhowmya
  - Ganavaridhi
  - Hindoladarbar
  - Ramya
  - Samantajingala
  - Bhanumanjari
  - Chayanattai
  - Maghathi
  - Mohanangi
  - Murali
  - Sharadabharana
  - Vikhavathi
  - Dheerahindolam
  - Shokavarali
  - Devanattai
  - Gambheeranattai
  - Ganaranjani
  - Nattai
  - Bhogasaveri
  - Jaganmohana
  - Bhoopalapanchamam
  - Godari
  - Jalasugandhi
  - Janavali
  - Karunamritavarshini
  - Kokilapanchamam
  - Varali
  - Chandrajyothi
  - Prabhavali
  - Poornalalitha
  - Poornapanchamam
  - Gandharva
  - Gomathi
  - Raghuleela
  - Kanchanabowli
  - Mahathi
  - Mechagandhari
  - Suvarnadeepakam
  - Vijayabhooshavali
  - Kanchanavathi
  - Arunangi
  - Bandhuvarali
  - Bhanudhanyasi
  - Bhanukeeravani
  - Chayaranjani
  - Dhowreyani
  - Hindusthani Todi
  - Jalakesari
  - Kumudhachandrika
  - Mahanandhini
  - Parpathi
  - Shekharachandrika
  - Ganahemavati
  - Indhudhanyasi
  - Shreekanti
  - Teevravahini
  - Abhiru
  - Rathika
  - Vijayashree
  - Deshamukhari
  - Dundubi
  - Jeevanthini
  - Suddha Gandhari
  - Abhiramam
  - Bhinnapauarali
  - Dharmini
  - Sudharmini
  - Narmada
  - Swaramanjari
  - Mandari
  - adhi Panchama
  - Basant Bahar
  - Bhogavasantha
  - Deepakam
  - Gamakapriya
  - Gamanapriya
  - Hamsanarayani
  - Indumathi
  - Kamalaptapriya
  - Kumudhakriya
  - Maruthi
  - Ponni
  - Prathapa
  - Puriya Dhanashree
  - Tandavapriya
  - Chintaramani
  - Hamsagamini
  - Lokaranjani
  - Meghashyamala
  - Patalambari
  - Raktimargini
  - Rasavinodini
  - Reethi Chandrika
  - Seemantinipriya
  - Sukhakari
  - Vedhaswaroopi
  - Alankari
  - Bhatiyar
  - Dvigandharabhooshani
  - Hamsanandi
  - Mechakangi
  - Padmakalyani
  - Poorvi Kalyani
  - Sharabadhvaja
  - Sohini
  - Vaishaka
  - Hemangi
  - Pooshakalyani
  - Sharadhyuthi
  - Suddhakriya
  - Sundarangi
  - Vijayavasantham
  - Deshavali
  - Vijayamalavi
  - Bhashini
  - Chintamani
  - Dhanakari
  - Garigadya
  - Gopikathilakam
  - Kokilanandhi
  - Rajeshwari
  - Samudrapriya
  - Shanmukhi (Trimoorti)
  - Sumanasaranjani
  - Vasukari
  - Ānandavalli
  - Ghantana
  - Jayachoodamani
  - Pranavapriya
  - Sarvangi
  - Seshanadam
  - Suddha
  - Sunadapriya
  - Urmika
  - Vijayasaraswathi
  - Chandrarekha
  - Hamsabhramari
  - Hemambari
  - Hemapriya
  - Kshemakari
  - Madhukowns
  - Shakthiroopini
  - Simharava
  - Vijayasaranga
  - Vijayashrangi
  - Yagini
  - Gowrikriya
  - Karmukhavati
  - Karpoora Bharani
  - Lalitasimharavam
  - Madhumalathi
  - Madhuvanthi
  - Moharanjani
  - Ranjani
  - Varada
  - Vijayanagari
  - Vishveshwarapriya
  - Amarasenapriya
  - Deshyaganavaridhi
  - Hamsanadham
  - Kaikavashi
  - Nuthanachandrika
  - Rathnasaranga
  - Kanakakusumavali
  - Shruthiranjani
  - Gopriya
  - Poornasaveri
  - Rathnabhanu
  - Suddha Saranga
  - Chitrachandrika
  - Hamsalatha
  - Kananapriya
  - Karunakari
  - Lalithangi
  - Ramani
  - Rathnakanthi
  - Raviswaroopini
  - Sajjananandhi
  - Skandamanorama
  - Bhagavataranjana
  - Bhogeeshwari
  - Bhooshavali
  - Dwigandharabhooshani
  - Gaganamohini
  - Gurupriya
  - Hrdhini
  - Mangalakari
  - Mukthidayini
  - Nadhabrahma
  - Pranavakari
  - Saraswathi
  - Triveni
  - Utthari
  - Vivahapriya
  - Amritha Behag
  - Aprameya
  - Bhoopkalyani
  - Chandrakantha
  - Hameer (Kalyan, Yaman That Janya)
  - Hameer Kalyani
  - Hamsakalyani
  - Kalyanadayini
  - Kannadamaruva
  - Kowmoda
  - Kunthalashreekanti
  - Mohana Kalyani
  - Mrganandhana
  - Nadhakalyani
  - Pramodhini
  - Saranga
  - Saranga Tarangini
  - Shilangi
  - Suddha Koshala
  - Sunadavinodini
  - Swayambhooshwara Raga
  - Vandanadharini
  - Yaman
  - Yaman Kalyani
  - Yamuna Kalyani
  - Amritavarshini
  - Chitrasindhu
  - Churnikavinodhini
  - Vijayakoshalam
  - Deepavarali
  - Jyothishmathi
  - Ramagiri
  - Dhwithiyapanchamam
  - Sumukham
  - Tavapriya
  - Marakathagowla
  - Thilakamandari
  - Ayodhya
  - Hamsagiri
  - Ishtarangini
  - Nagagiri
  - Kanakangi
  - Rathnangi
  - Ganamoorti
  - Vanaspati
  - Manavati
  - Tanaroopi
  - Senavati
  - Hanumatodi
  - Dhenuka
  - Natakapriya
  - Kokilapriyaa
  - Rupavati
  - Gayakapriya
  - Vakulabharanam
  - Mayamalava Gowla
  - Chakravakam
  - Sooryakantam
  - Hatakambari
  - Jhankaradhvani
  - Natabhairavi
  - Keeravani
  - Kharaharapriya
  - Gowri Manohari
  - Varunapriyaa
  - Mararanjani
  - Charukeshi
  - Sarasangi
  - Harikambhoji
  - Dheera Shankarabharanam
  - Naganandhini
  - Yagapriya
  - Ragavardhani
  - Gangeyabhushani
  - Vagadeeshwari
  - Shulini
  - Chalanattai
  - Salagam
  - Jalarnavam
  - Jhalavarali
  - Navaneetham
  - Pavani
  - Raghupriyaa
  - Ghavambhodi
  - Bhavapriya
  - Shubhapanthuvarali
  - Shadvidhamargini
  - Suvarnangi
  - Divyamani
  - Dhavalambari
  - Namanarayani
  - Panthuvarali (Kamavardhani)
  - Ramapriya
  - Gamanashrama
  - Vishvambhari
  - Shyamalangi
  - Shanmukhapriyaa
  - Simhendramadhyamam
  - Hemavathi
  - Dharmavathi
  - Neethimathi
  - Kanthamani
  - Rishabhapriya
  - Lathangi
  - Vachaspathi
  - Mechakalyani
  - Chitrambari
  - Sucharitra
  - Jyothiswaroopini
  - Dhatuvardhani
  - Nasikabhooshhani
  - Kosalam
  - Rasikapriya
